### ISSUE TITLE
Not able to handle complex strings

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#13]
Not sure which part is unimplemented.

Examples of strings that cause exceptions to throw:

`return "[year][seperator][((month < 10) ? "0[month]" : month)][seperator][((day < 10) ? "0[day]" : day)]"`

`return "[day] day[(day != 1) ? "s":""][hourT][minuteT][secondT]"`

`hourT = " and [hour] hour[(hour != 1) ? "s":""]"`

`user << browse("<ol><li>[lines.Join("</li><li>")]</li></ol>", "window=[rustg_url_encode("stats:[REF(stats)]")]")`

`var/static/regex/bad_chars_regex = regex("\[^#%&./:=?\\w]*", "g")`

**Comment by ike709** [comment]
I'm assuming it has to do with ternaries inside of strings.

**Comment by ike709** [comment]
Or just nested strings in general.

**Comment by ike709** [comment]
Weirdly enough some of these seem fine when I just toss them in TestGame's code.dm

**Comment by wixoaGit** [comment]
Is this still an issue? I haven't been able to reproduce this.
