### ISSUE TITLE
`list` can't be used as the variable name of a list

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#137]
```
proc/tg_list2text(list/list, glue=",")
	if(!istype(list) || !list.len)
		return
```
Second line errors with:
![image](https://user-images.githubusercontent.com/5714543/120130716-79eba280-c18c-11eb-86e6-72371d96ee90.png)

**Comment by wixoaGit** [comment]
Fixed by 566ad3567ce924632095b3259247035d9ad17da6.
