### ISSUE TITLE
Compiler chokes on errors

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#138]
In BYOND the compiler will print up to 100 errors. In OpenDream only a few errors at a time seem to be printed at a time. 

As far as I can tell it's often (but not always) only printing errors from the first line that has any errors.

**Comment by wixoaGit** [comment]
As of #325 the parser now _attempts_ to recover from errors by trying to skip to the next statement. There's still a lot to be left desired, but the compiler no longer breaks at the first error.
