### ISSUE TITLE
`.` can't be used in a formatted string

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#139]
Sample code:
```
/proc/main()
  . = 5
  world.log << "[.]"
```
Error:
![image](https://user-images.githubusercontent.com/5714543/120132072-4bbb9200-c18f-11eb-8f85-8d6f6df6599e.png)

**Comment by wixoaGit** [comment]
This was fixed by 283471f8eb7a9387847ce62c3e539356954076ff.
