### ISSUE TITLE
multiple variable setting on a single line isn't supported

### ISSUE THREAD

**Issue by ZeWaka** [wixoaGit/OpenDream#18]
ex.
`var/i, ch, len = length(list)`

**Comment by ike709** [comment]
Christ why is this valid syntax

**Comment by ike709** [comment]
I started looking into this and it looks like either `ProcStatement()` or `ProcVarDeclaration()` need to be modified. However, since the latter only returns *one* `DMASTProcStatementVarDeclaration` and the former only returns *one* `DMASTProcStatement` I'm not really sure how to implement this.

**Comment by ZeWaka** [comment]
or just not support it 😎

**Comment by wixoaGit** [comment]
Support for this was added in 3c844f26350c3be4ede70515565f72a278e8e00c and 075f1c5ccf641269b49a1fc84429d1ef24166924.
