### ISSUE TITLE
CurrentLine doesn't match actual line number

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#21]
https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/game/objects/items/devices/scanners.dm causes an exception due to #10 

`WriteSourceAndLine()` and the `CurrentLine` var both say 255. However, the actual problem line is 262.

Looking at the actual lines shows that they are in fact numbered incorrectly. I would say that this is entirely due to multiline strings, but the `var/list/dmgreport = list()` line doesn't match up either and it's before the multiline. 

EDIT: However, there's also some multiline strings earlier in the file that could be contributing to the line number being off. Looks like it might entirely be the fault of multiline strings.

![image](https://user-images.githubusercontent.com/5714543/117257388-6e1cf280-ae11-11eb-87d8-82d7299ae35c.png)

**Comment by wixoaGit** [comment]
This was fixed in be69c5d384f241e0a14b4c0bd79bba6472689854

The preprocessor would previously combine lines ending in backslashes before lexing them, which would give incorrect line numbers. The combining is now done in the preprocessor's lexer.
