### ISSUE TITLE
Named `elem`s cause errors in DMF parsing

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#219]
`Error at interface.dmf:534:14: Expected EOF`

Line 534: `elem "s_key"`

**Comment by ike709** [comment]
Actually the issue may be duplicated elem names, since the two that threw errors were defined twice

**Comment by ike709** [comment]
Nope it still errors without dupes.

**Comment by ike709** [comment]
Changing it to something like
```
elem
    name = "s_key"
```
just causes a different error saying it expected a name.

**Comment by wixoaGit** [comment]
Fixed in ace2c9ff5114d4449cbb3b6e9e4c6cf84570e6b6.
