### ISSUE TITLE
Expected EOF error with one-line procs

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#24]
`/proc/rustg_log_close_all() return call(RUST_G, "log_close_all")()` from https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/__DEFINES/rust_g.dm#L103

Causes `Expected EOF`.

**Comment by wixoaGit** [comment]
This was fixed in 8b4d3c1fa7a8574f191422a10fa646ce7c18841f.
