### ISSUE TITLE
Index out of range exception

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#257]
Code:
```
/proc/flick_overlay(image/I, list/show_to, duration)
    for(var/client/C in show_to)
        C.images += I
    addtimer(CALLBACK(GLOBAL_PROC, /proc/remove_images_from_clients, I, show_to), duration, TIMER_CLIENT_TIME)
```

![image](https://user-images.githubusercontent.com/5714543/127758428-d44fbc04-b698-4f27-b76d-567867b8738e.png)

BeeStation

**Comment by wixoaGit** [comment]
Exception fixed by f5975c3849e0cb2143334283d93a869d58a652bc, issue with code snippet fixed by 610f69ea209ea8b30613303decaab5b82d1f0f8b.
