### ISSUE TITLE
`thing.proc/procname` errors

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#261]
Code: `INVOKE_ASYNC(query, /datum/DBQuery.proc/warn_execute)`
Preprocessor: `world.ImmediateInvokeAsync(query, /datum/DBQuery.proc/warn_execute)`

![image](https://user-images.githubusercontent.com/5714543/127759598-fe2ab68a-7cab-48cd-ba23-26b446ba220f.png)

**Comment by wixoaGit** [comment]
Fixed in aadc87d24123ae2c8cf192666769814265ac35bf.
