### ISSUE TITLE
Exception with `global` in a define

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#266]
![image](https://user-images.githubusercontent.com/5714543/127814597-39c2959f-04d0-40fe-83d8-2b3dd6f3bddd.png)

`#define CONFIG_GET(X) global.config.Get(/datum/config_entry/##X)`
```
/proc/log_admin(text)
	GLOB.admin_log.Add(text)
	if (CONFIG_GET(flag/log_admin))
		WRITE_LOG(GLOB.world_game_log, "ADMIN: [text]")
```

**Comment by wixoaGit** [comment]
Same issue as #195.
