### ISSUE TITLE
Implement a `set` for unsupported builtins

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#319]
Putting this in an issue so we don't forget about it. Dependent on the AST error handler getting support for warnings.

![image](https://user-images.githubusercontent.com/5714543/128613620-224ae0e1-f0b3-4f63-a9bf-b1bcaf8a6e3e.png)

**Comment by wixoaGit** [comment]
Added in 68d1c063b68c276263ef6d6f59fd2515c9a1315d.
