### ISSUE TITLE
Funky bracket var declaration syntax doesn't work

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#320]
`var/{flatX1=1;flatX2=flat.Width();flatY1=1;flatY2=flat.Height()}`

![image](https://user-images.githubusercontent.com/5714543/128653360-fa1ab7a6-e864-4bb2-8d91-61d45418c057.png)

**Comment by wixoaGit** [comment]
Note that this is just a different way to write this:
```
var
    flatX1 = 1
    flatX2 = flat.Width()
    flatY1 = 1
    flatY2 = flat.Height()
```

**Comment by martinlyra** [comment]
I recall that SpacemanDMM did not support bracket declaration, so one of the solutions was to declare the variables individually.
