### ISSUE TITLE
FILE_DIRs aren't handled

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#33]
These are optionally used by the Dream Maker IDE but are otherwise useless and can be ignored.

**Comment by ike709** [comment]
Even when file dirs are disabled in the IDE, the .dme still contains `#define FILE_DIR .`
All other `FILE_DIR` defines should be ignored.

**Comment by wixoaGit** [comment]
Multiple defines with the same name no longer causes problems, the second define will override the first (aeee0abffcb9f60e5b6a99453f5a3d133648dbbc)

The FILE_DIR define still causes no change in behavior
