### ISSUE TITLE
I'm poking through DotTrace/DotMemory here's what I'm finding

### ISSUE THREAD

**Issue by PJB3005** [wixoaGit/OpenDream#342]
These are just various optimization potentials I'm finding by poking through DotTrace/DotMemory on TG:

- [x] `DMOpcodeHandlers.CreateList()` takes a whopping 7.2% of startup time. This is a lot. Could we do without running `InitProc()` and such to speed this up with a fast path? Lists are quite critical and people aren't gonna be defining `/list/New()` anyways.
- [x] `DreamList` always allocates `_associativeValues` even if the list is never used as assoc values. Making these null until first used would probably save ~100 MB alone.
- [x] Tons of allocations are made in `Stack<object>`, specifically `DMProcState._stack`. It's just allocating the backing array really. Furthermore pushing onto this stack is a boxing operation despite most of the values being pushed on being structs. Might be worth making this stack a bunch of unions or something and pooling the stacks. Doing this would reduce a massive amount of allocations I bet.

About 1 GB of total memory is OpenDream, the rest is misc stuff and Robust.

**Comment by ike709** [comment]
Second bullet point fixed in #343

**Comment by ike709** [comment]
First point addressed in #494 and https://github.com/wixoaGit/OpenDream/commit/4d72870341f0101e042c1e3d7eb2dfdbfd53b286

**Comment by wixoaGit** [comment]
The stack was pooled in 51d0f8ec0d53a932b6a294f3e91ffd8acf067fe7 and as of 65c4ca98d61193d241b9362f35312903c1f143d5 no longer boxes when pushed to.
