### ISSUE TITLE
Preproc handles defines differently based on whitespace

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#350]
`#define HEALTH_THRESHOLD_DEAD -100`
`(L.health-HEALTH_THRESHOLD_DEAD)` is treated as (`L.health-- 100)` while if you put a space on either side it's properly treated as `(L.health - -100)`

I wonder if we could just have the preproc wrap all defines in parentheses?

**Comment by wixoaGit** [comment]
Fixed by f611581142e9997f919b4e6602599540b71be432.
