### ISSUE TITLE
References to world in global initializers cause nullref in compiler nullref

### ISSUE THREAD

**Issue by PJB3005** [wixoaGit/OpenDream#361]
Guilty code (from NT). Note that this is a global variable definition:

![image](https://user-images.githubusercontent.com/8107459/131416661-735e1b5a-384b-4aef-8bd2-ded0ea890ecc.png)

There's no proc so the resolution of `world` causes a nullref looking up the proc scope.

**Comment by wixoaGit** [comment]
Fixed by fe35e2f95ddc5f720da87924e829e391fcd8054e.
