### ISSUE TITLE
Preprocessor exception with long raw strings

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#366]
`GLOBAL_DATUM_INIT(filename_forbidden_chars, /regex, regex(@{""|[\\\n\t/?%*:|<>]"}, "g"))`
`Unhandled exception. System.Exception: Missing ')' in macro call`

Removing the `@{}` (and extra " resulting from that) fixes it.

**Comment by wixoaGit** [comment]
This has been fixed.
