### ISSUE TITLE
Add a `--verbose` flag

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#378]
Right now it's hard to tell if the compiler is frozen or just taking a while. It'd be useful to add an arg that makes it actually output some form of status updates throughout the process.

**Comment by wixoaGit** [comment]
What sort of status update should it output? Every file that gets `#include`d?

**Comment by ike709** [comment]
Ideally the stage of compilation it's in and the file it's working on, and maybe prefix the status with the time since start.

**Comment by wixoaGit** [comment]
Added by d1371065362f3a0aec0bf84c4c67d043028231dd
