### ISSUE TITLE
Unimplemented DMASTVisitor methods

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#40]
Unimplemented DMASTVisitor methods are the only thing stopping OpenSS13 from compiling, aside from #34 which can easily be sidestepped by modifying the DM code.

However, the DMASTVisitorObjectBuilder and DMASTVisitorProcBuilder go *way over my head* so I don't think there's many more methods here that I can implement myself.

**Comment by wixoaGit** [comment]
As of 39a4f4999f7699f1cb9a20a12defad1bc5e1f7c8, unimplemented DMASTVisitor methods are no a problem with compiling OpenSS13.

What's now stopping OpenSS13 from compiling is the absence of built-in vars/procs and #45.
