### ISSUE TITLE
Proc/Var declaration blocks aren't handled correctly

### ISSUE THREAD

**Issue by wixoaGit** [wixoaGit/OpenDream#45]
```dm
/datum
	var
		one = 1
		two = 2
```
The compiler interprets this as a `/datum/var` object that overrides variables `one` and `two`. What it should do instead is define the variables `one` and `two` on `/datum`.

The same problem exists for proc definitions.

**Comment by ike709** [comment]
The curse of relative pathing.

**Comment by ike709** [comment]
According to DreamChecker there's 788 instances of relative pathing in OpenSS13, so yeah... this issue is a bit of a blocker.

**Comment by ZeWaka** [comment]
I guess we just need to treat `var` as a special case in which it's not a relative object definition.

**Comment by wixoaGit** [comment]
I'm thinking the parser should keep track of the full path of whatever it's currently parsing. If the full path contains `var` or `proc` then it should be treated as a definition rather than an override.

**Comment by wixoaGit** [comment]
This was fixed in ff2f3499e055d1f5e0d4fbf7b05a6ec11e17217e.
