### ISSUE TITLE
Special loops like `for (var/client/C)` aren't supported

### ISSUE THREAD

**Issue by ZeWaka** [wixoaGit/OpenDream#50]
title

```
Error at code\game\admin\ban.dm:126:20: Expected 'to'
Error at code\game\admin\ban.dm:126:20: Expected an expression
```

**Comment by ike709** [comment]
> this is valid DM

hnnnnnnnnng

**Comment by ZeWaka** [comment]
it's basically just an `in world` loop

**Comment by wixoaGit** [comment]
`for (var/client/C)` and `for (var/client/C in world)` do not have the same behavior.

**Comment by ZeWaka** [comment]
Ahh, I was unaware `in world` didn't act like I thought it did. That sucks :/

**Comment by ike709** [comment]
So how many of these are there and is there any documentation on how they work?

**Comment by wixoaGit** [comment]
After a quick look through the ref, all I found on loops like this is in an example code snippet. It doesn't have any kind of explanation. 
http://www.byond.com/docs/ref/#/proc/for/list

From what I can tell, they work with any type.
`for (var/client/C)` will loop through all clients
`for (var/datum/D)` will loop through all instances of datums (excluding atoms, which inherit from datums but aren't datums?)
`for (var/datum/subtype/D)` will loop through all `/datum/subtype` instances
And etc

**Comment by ike709** [comment]
Thanks, I hate it.

**Comment by ike709** [comment]
`for(var/client/C)` is significantly more important than datums at the moment
