### ISSUE TITLE
Copy CIL's `.maxstack`

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#502]
Credit to PJB for all of this, I'm just documenting it in a github issue so it isn't lost. Relevant Discord discussion: https://discord.com/channels/847318834952405042/847318834952405045/916359065037328484

tl;dr, the compiler needs to figure out how big a stack needs to be and then pass it to the interpreter so the initial allocation can be the size it needs and we don't have to do any further allocations

**Comment by wixoaGit** [comment]
Implemented in 51d0f8ec0d53a932b6a294f3e91ffd8acf067fe7
