### ISSUE TITLE
Error with bodyless `for` loop

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#527]
Code:
```
/obj/item/assembly/health/process()
	if(!scanning || !secured)
		return

	var/atom/A = src
	if(connected && connected.holder)
		A = connected.holder

	for(A, A && !ismob(A), A=A.loc);
	// like get_turf(), but for mobs.
	var/mob/living/M = A

	if(M)
		health_scan = M.health
		if(health_scan <= alarm_health)
			pulse()
			audible_message("[bicon(src)] *beep* *beep*")
			toggle_scan()
		return
	return
```
Error: `Unknown identifier "M"` at `if(M)`

Commenting out the `for` loop fixes it. Presumably bodyless for loops aren't being handled properly.

**Comment by ike709** [comment]
It's calling `ProcStatement()` which is pulling a following statement into the for body. 

Needs an indentation check that it is actually part of the body.

**Comment by Just-a-Unity-Dev** [comment]
Close due to #414 fixing this?

**Comment by wixoaGit** [comment]
Yes, it's fixed now
