### ISSUE TITLE
`Shrinkstack()` exception

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#598]
Just opening this so it isn't lost in Discord.

See: https://discord.com/channels/847318834952405042/847318834952405045/943703323691876453

**Comment by ike709** [comment]
This is caused by `||=` being used to assign to a dereference.

Works: `some_var ||= list()`
Broke: `some_obj.some_var ||= list()`

**Comment by wixoaGit** [comment]
As of 70953a678c14f0d9df21603fe2086cc026ba4619 this is no longer an exception. It's now a compiler error.
