### ISSUE TITLE
`calling initial() on a list index returns the current value` warning shouldn't apply to `vars`

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#685]
`calling initial() on a list index returns the current value` is accurate for declared lists, but the `vars` list does support `initial()` properly

Right now OpenDream still throws the warning for `vars` and returns the current value of the var rather than the initial var.

**Comment by wixoaGit** [comment]
Unfortunately there's not going to be any good way to differentiate between `vars` and any other list on the compiler's side.

**Comment by ike709** [comment]
Need to also check if `issaved()` works on `vars`
