### ISSUE TITLE
Unknown identifier with static vars

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#706]
Compiling /vg/station produces the following error:
`Error at code\modules\client\preferences\subsections\limbs.dm:28:29: Unknown identifier "peg_limb_data"`
at the following location in `limbs.dm`:
```
22 var/static/list/peg_limb_data = list(
23	"internal_name" = "peg",
24 	"mode" = LIMB_MODE_SPECIAL_SNOWFLAKE,
25 )
26 
27 var/static/list/leg_configurable_states = list(
28 	"Peg leg" = peg_limb_data,
29 )
```

**Comment by ike709** [comment]
Dupe of https://github.com/wixoaGit/OpenDream/issues/693

**Comment by wixoaGit** [comment]
> Dupe of #693 ?

They are static vars, nothing here is required to be constant.

**Comment by Altoids1** [comment]
I didn't get a compiler error. I think this is fixed?

**Comment by Hinaichigo** [comment]
Yep, it seems like it.
