### ISSUE TITLE
obounds() unimplemented

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#707]
It seems like the native proc `obounds()` is unimplemented and gives an error instead of a warning.
Compiling /vg/station errors:
`Error at code\game\atoms_movable.dm:471:24: Type /atom/movable does not have a proc named "obounds"`
at the following location:
```
470 if(isturf(loc)) //obounds() provides nonsense results when Ref.loc isn't a turf.
471 	uncrossing = obounds(src)
```

**Comment by Hinaichigo** [comment]
Would this be an issue to report with Robust Toolbox instead?

**Comment by wixoaGit** [comment]
> Would this be an issue to report with Robust Toolbox instead?

RobustToolbox has nothing to do with DM code. Unimplemented proc warnings are handled in OpenDream by defining the proc and setting the `opendream_unimplemented` attribute to `TRUE` (examples of this can be found [here](https://github.com/wixoaGit/OpenDream/blob/master/DMCompiler/DMStandard/UnsortedAdditions.dm)). We don't have a definition for `obounds()` so it's an error instead.
