### ISSUE TITLE
Overriden vars don't keep type information

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#738]
When trying to compile /vg/station, the following error occurs:
`Error at code\modules\cmc\crew.dm:32:15: An inferred new requires a type!`
at the following location:
```
21 /obj/machinery/computer/crew
...
32 	_using = new()
```
`_using` is defined in `code/game/objects/objs.dm` as:
`var/list/mob/_using`
In game, interacting with the crew monitoring computer adds the user's mob to `_using`

**Comment by wixoaGit** [comment]
This is because override vars aren't keeping type information.
