### ISSUE TITLE
Undefined variables throw an unhelpful exception

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#76]
Currently if you assign a value to an undefined var you get `Unhandled exception. System.Exception: Invalid identifier "[varname]"
`

This provides no useful info like file or line number.

**Comment by wixoaGit** [comment]
There have been a lot of improvements to compile-time error handling. Assigning a value to an undefined var is no longer an unhandled exception and gets you a more useful `Error at code.dm:18:4: Unknown identifier "[varname]"`.
