### ISSUE TITLE
Can't enumerate `as anything in typesof()` for loop

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#816]
Example code:
```
#define subtypesof(typepath) ( typesof(typepath) - typepath )

/datum/circuit_composite_template
    var/datatype

/datum/circuit_composite_template/assoc_list
    datatype = 5

/proc/testme()
    world.log << "yeet"
    for(var/datum/circuit_composite_template/type as anything in subtypesof(/datum/circuit_composite_template))
        if(!initial(type.datatype))
            world.log << "A"
            continue
        world.log << "B"
    world.log << "done"
```
This code runtimes because `initial()` is being passed `null` instead of the `/datum/circuit_composite_template/assoc_list` typepath

**Comment by ike709** [comment]
Notably this is being treated as a standard for loop instead of a list enumerator

**Comment by SpaceManiac** [comment]
Possibly related to the infinite loop exhibited by `Content.Tests/DMProject/Broken Tests/Statements/For/as_empty_paren.dm`

**Comment by wixoaGit** [comment]
#818 fixes this and the mentioned test.
