### ISSUE TITLE
`input() in list()` should display a selection of list contents

### ISSUE THREAD

**Issue by amylizzle** [wixoaGit/OpenDream#819]
`input("Prompt message", "Prompt title", null) in list("Option 1", "Option 2", "Option 3")` should produce a similar UI to this (byond version):

![image](https://user-images.githubusercontent.com/3855802/192157718-da6ac85f-6a01-4391-b518-73f439d37638.png)

**Comment by wixoaGit** [comment]
Added in d8d10688c3e8c217cfc86ac743e6d0aef9d50381.

![image](https://user-images.githubusercontent.com/30789242/192166862-272b87ca-9c6c-409a-a068-1c801a5364f0.png)
