### ISSUE TITLE
Comparison operators do not yet have any constant folding

### ISSUE THREAD

**Issue by Altoids1** [wixoaGit/OpenDream#828]
This is preventing #827's preprocessor from handling these operators correctly.

This is caused by them having missing `TryAsConstant()` overrides.

**Comment by ike709** [comment]
Specifically just `==` and `!=`?

**Comment by Altoids1** [comment]
I think all inequality operations. ==, <=, <, >, !=, and ~=.

**Comment by wixoaGit** [comment]
Closing in favor of #833
