### ISSUE TITLE
Error with \the in string not preceding interpolated expression

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#847]
When trying to compile /vg/station, the following error occurs:
`Error at code\game\turfs\unsimulated\snow.dm:237:87: Macro "\the" must precede an interpolated expression`

The corresponding lines:
```
237	user.visible_message("<span class='notice'>[user] finishes \the log wall.</span>", \
238		"<span class='notice'>You finish the log wall.</span>")
```

**Comment by ike709** [comment]
This is invalid DM that BYOND silently ignores. `\the` should be changed to `the`.

When pragmas are in we can silence the error by default, but it's still invalid DM that needs to be fixed.

**Comment by ike709** [comment]
There, I made the fix PR for you on /vg/.

**Comment by Altoids1** [comment]
I intentionally decided (with Wixoa's consent) to not support this, because it is honestly invalid and produces undefined behaviour (several flavours of it, actually) that the user likely does not want to happen.
