### ISSUE TITLE
move_up doesnt consider if the zlevel above it exists

### ISSUE THREAD

**Issue by redmoogle** [wixoaGit/OpenDream#91]
`Exception while running verb "move_up": Exception while running proc 'step' on object of type '/mob': Exception while running proc 'Move' on object of type '/mob': Cannot dereference 'Enter' on a null object`

**Comment by ZeWaka** [comment]
this is an issue with Move/Enter, not the verb.

**Comment by wixoaGit** [comment]
Fixed in 6d723d6c30d29ab709140a5ada53123e09693a02.
